config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/participants', to: 'participants#index'
  get '/participants/:id', to: 'participants#show', as: 'participant'
  post '/participants/email', to: 'participants#email'
  resources :participants do
    resources :participant_wishes
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_many :participant_wishes
  has_one :participant_assigns
end

app/controllers/participants_controller.rb
require 'uri'

class ParticipantsController < ApplicationController
  def index
    @participants = Participant.all

    # allow only for admin
    if (!@participant_you.admin)
      Rails.logger.debug("Participant id #{@participant.id} is not you #{@participant_you.id} and not your kriskringle, redirecting")
      redirect_to :root
      return
    end

  end

  def show
    @participant = Participant.find(params[:id])

    # allow only if this is you or your kriskringle
    if (@participant.id != @participant_you.id) && (@participant.id != @participant_kriskringle.id) && (!@participant_you.admin)
      Rails.logger.debug("Participant id #{@participant.id} is not you #{@participant_you.id} and not your kriskringle, redirecting")
      redirect_to :root
      return
    end

    @participant_wishes_links = {}
    @participant.participant_wishes.each { |pw|

      pw.description.sub!(/\<.*\>/, '')

      while pw.description.match(/(http|https|www\.)(:\/\/)?[\S]+/) { |m|
          pw.description.sub!(/(http|https|www\.)(:\/\/)?[\S]+/, '')
          if @participant_wishes_links[pw.id.to_s].nil?
            @participant_wishes_links[pw.id.to_s] = []
          end
          m_text = m.to_s
          m_text.sub!(/^www/, 'http://www')
          @participant_wishes_links[pw.id.to_s] << m_text
        }

        Rails.logger.debug("Have participant wishes links #{@participant_wishes_links[pw.id.to_s]}")
      end
    }
    Rails.logger.debug("Have all participant wishes links #{@participant_wishes_links}")

  end

  def email
    Rails.logger.debug("Emailing participants")

    set_participant_you()
    check_participant_you()
    set_participant_kriskringle()

    # allow only if you are an admin
    if (!@participant_you || !@participant_you.admin)
      Rails.logger.debug("Participant is null or not and admin, redirecting")
      redirect_to :root
      return
    end

    params[:participants].each { |participant|

      if params[:participants][participant][:email].to_i == 1

        participant = Participant.find(participant)

        Rails.logger.debug("Sending email to participant #{participant.name}")

        assigned_participant = ParticipantAssign.find_by participant_id: participant.id
        if assigned_participant
          participant_assign = Participant.find_by id: assigned_participant.assign_participant_id
        end

        KrisKringleMailer.kriskringle_assigned_email(participant, participant_assign).deliver_later(queue: 'mailers')
      end
    }

    redirect_to participants_path
    return
  end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/index.html.erb
<h1>Participant List</h1>
<%= form_tag participants_email_path do %>
  <table class="table">
    <tr>
      <th>Participant</th>
      <th>Wish Count</th>
      <th>Send Email</th>
    </tr>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= link_to participant.name, participant_path(participant) %>
          <div><%= participant.email %></div>
        </td>
        <td><%= participant.participant_wishes.size %></td>
        <%= fields_for "participants[]", participant do |p| %>
          <td><%= p.check_box :email, {}%></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Email Participants", class: "btn btn-default" %>
<% end %>

app/views/participants/show.html.erb
<!--                    -->
<!-- participant name -->
<!--                    -->
<div id="participant">
  <h3>Participant</h3>
  <%= @participant.name %>
</div>
<div class="row">
  <div id="participant-wishes" class="col-md-12 col-sm-12 col-xs-12">
    <table class="table">
      <tr>
        <th colspan="3">
          Wishes
      </th>
      </tr>
      <% if @participant.participant_wishes.length == 0 %>
        <tr>
          <td colspan="3">No wishes have been entered yet</td>
        </tr>
      <% end %>
      <!--                    -->
      <!-- participant wishes -->
      <!--                    -->
      <% @participant.participant_wishes.each do |pw| %>
        <tr>
          <td>
            <%= pw.description %>
            <% if @participant_wishes_links["#{pw.id}"] %>
              <% @participant_wishes_links["#{pw.id}"].each do |l| %>
                <div>
                  <a href="<%= l %>" target="_outside"><%= l %></a>
                </div>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_participant_participant_wish_path(@participant, pw) %></td>
          <td><%= link_to 'Delete', [@participant, pw], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<!--                    -->
<!-- add wishes -->
<!--                    -->
<% if @participant.id == @participant_you.id %>
  <div id="participant-add-wish">
    <%= link_to 'Add a wish', new_participant_participant_wish_path(@participant) %>
  </div>
<% end %>