config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/participants', to: 'participants#index'
  get '/participants/:id', to: 'participants#show', as: 'participant'
  post '/participants/email', to: 'participants#email'
  resources :participants do
    resources :participant_wishes
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  # override superclass so we don't redirect ourselves
  # up our own arse
  def check_participant_you

    Rails.logger.debug("Have cookie digest #{cookies[:digest]}")

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%if @participant_you %>
  <div id="participant-kriskringle">
    Hello, <%= @participant_you.name %>
    <% if @participant_you.admin %>
      (Admin)
    <% end %>
  </div>
<% end %>
<div id="description">
  Secret Santa is a Christmas tradition in which family members are randomly assigned a person to whom they anonymously give a gift.
  </div>
<%if @participant_you %>
  <div id="participant-kriskringle">
    <%if @participant_kriskringle %>
      <div>Your Kris Kringle this year is</div>
      <div id="participant-assigned">
        <h2><%= @participant_kriskringle.name %>!</h2>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-5 col-sm-5 hidden-xs">
      <div id="content-decoration">
        <!-- christmas tree goes here -->
      </div>
    </div>
    <div class="col-md-7 col-sm-7">
      <div id="participant-gift-limit">
        <h3>Gift price limit</h3>
        <p>
          The gift limit this year is approximately <b>$30.00</b>
        </p>
      </div>
      <div id="participant-options">
        <h3>What next?</h3>
        <ul id="participant-menu">
          <li><%= link_to "Edit your wish list", participant_path(@participant_you) %></li>
          <% if @participant_kriskringle %>
            <li><%= link_to "View your Kris Kringles wish list", participant_path(@participant_kriskringle) %>
            </li>
          <% end %>
        </ul>
      </div>
      <%if @participant_you.admin %>
        <div id="admin-options">
          <h3>Admin options</h3>
          <ul>
            <li> <%= link_to 'View participants list', participants_path %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<%if !@participant_you || @participant_you.admin %>
  <div id="participant-key">
    <h3>Enter participant key</h3>
    <%if !@participant_you %>
      <p>
        If you are a participant in this years Christmas Kris Kringle you will have received an email with a link or a key to access your account. Enter the key found in the email below!
      </p>
    <% end %>
    <%= form_tag(:root, method: "get") do %>
      <div class="form-group">
        <input name="key" class="form-control" type="textfield"/>
      </div>
      <input type="submit" class="btn btn-default" value="Submit"/>
    <% end %>
  </div>
<% end %>